CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    total_required_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
    theme_mode VARCHAR(10) NOT NULL DEFAULT 'light',
    progress_color_hex VARCHAR(7) NOT NULL DEFAULT '#0d6efd'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS time_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    time_in DATETIME NOT NULL,
    time_out DATETIME NULL,
    hours_rendered DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_time_logs_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
